version: '3.4'

networks:
    mywebapp-dev:
        driver: bridge

services:
    mywebapp:
        image: ${DOCKER_REGISTRY-}mywebapp
        container_name: imagesharing-site
        depends_on:
            - "mywebapp_db"
        build:
            context: .
            dockerfile: MyWebApp/Dockerfile
        networks:
            - mywebapp-dev

    mywebapp_db:
        image: postgres:15
        container_name: imagesharing-db
        networks:
            - mywebapp-dev
        restart: always